### ISSUE TITLE
Unable to connect at localhost:8899

### ISSUE THREAD

**Issue by josephtaylor-mn** [kubeshark/kubeshark#1295]
When I run the command `kubeshark tap -A` it appears to find my cluster properly and all of the pods. But there are some errors describing issues connecting to proxy. I am unsure how to proceed.

**To Reproduce**
1. Run `kubeshark tap -A`

**Expected behavior**
Accessing the dashboard with traffic visible at localhost:8899

**Logs**
Upload logs:
➜  ~ kubeshark tap -A --set dump-logs=true
2023-01-10T10:32:53-06:00 INF versionCheck.go:23 > Checking for a newer version...
2023-01-10T10:32:53-06:00 WRN config.go:142 > error="flag \"dump-logs\" not found"
2023-01-10T10:32:53-06:00 INF tapRunner.go:45 > Using Docker: registry=docker.io/kubeshark tag=latest
2023-01-10T10:32:53-06:00 INF tapRunner.go:53 > Kubeshark will store the traffic up to a limit (per node). Oldest TCP streams will be removed once the limit is reached. limit=200MB
2023-01-10T10:32:53-06:00 INF common.go:70 > Using kubeconfig: path=/Users/josephtaylor/.kube/config
2023-01-10T10:32:54-06:00 INF tapRunner.go:74 > Targetting pods in: namespaces=[""]
2023-01-10T10:32:54-06:00 INF tapRunner.go:124 > New pod: application-controller-manager-64446698d9-qbk6b
2023-01-10T10:32:54-06:00 INF tapRunner.go:124 > New pod: application-controller-manager-64446698d9-xqj2l
2023-01-10T10:32:54-06:00 INF tapRunner.go:124 > New pod: cert-manager-677874db78-crn5b
2023-01-10T10:32:54-06:00 INF tapRunner.go:124 > New pod: cert-manager-cainjector-6c5bf7b759-r5ckw
2023-01-10T10:32:54-06:00 INF tapRunner.go:124 > New pod: cert-manager-webhook-5685fdbc4b-ccffg
2023-01-10T10:32:54-06:00 INF tapRunner.go:124 > New pod: analyze-front-cf479bbb5-4ghxb
2023-01-10T10:32:54-06:00 INF tapRunner.go:84 > Waiting for the creation of Kubeshark resources...
2023-01-10T10:32:54-06:00 INF createResources.go:108 > Successfully created a pod. pod=kubeshark-hub
2023-01-10T10:32:55-06:00 INF createResources.go:120 > Successfully created a pod. pod=kubeshark-front
2023-01-10T10:32:55-06:00 INF createResources.go:69 > Successfully created a service. service=kubeshark-hub
2023-01-10T10:32:55-06:00 INF createResources.go:76 > Successfully created a service. service=kubeshark-front
2023-01-10T10:32:55-06:00 INF tapRunner.go:217 > Added pod. pod=kubeshark-hub
2023-01-10T10:32:55-06:00 INF tapRunner.go:297 > Added pod. pod=kubeshark-front
2023-01-10T10:33:00-06:00 INF proxy.go:29 > Starting proxy... namespace=kubeshark service=kubeshark-hub src-port=8898
2023-01-10T10:33:00-06:00 INF proxy.go:29 > Starting proxy... namespace=kubeshark service=kubeshark-front src-port=8899
E0110 10:33:02.027683   88162 proxy_server.go:147] Error while proxying request: context canceled
E0110 10:33:03.225715   88162 proxy_server.go:147] Error while proxying request: context canceled
E0110 10:33:05.029338   88162 proxy_server.go:147] Error while proxying request: context canceled
E0110 10:33:06.227940   88162 proxy_server.go:147] Error while proxying request: context canceled
2023-01-10T10:33:07-06:00 ERR common.go:33 > Couldn't connect using proxy, stopping proxy and trying to create port-forward..
2023-01-10T10:33:07-06:00 INF proxy.go:117 > Starting proxy using port-forward method... dst-port=80 namespace=kubeshark pod=kubeshark-hub src-port=8899
E0110 10:33:08.031641   88162 proxy_server.go:147] Error while proxying request: context canceled
2023-01-10T10:33:09-06:00 ERR common.go:33 > Couldn't connect using proxy, stopping proxy and trying to create port-forward..
2023-01-10T10:33:09-06:00 INF proxy.go:117 > Starting proxy using port-forward method... dst-port=8898 namespace=kubeshark pod=kubeshark-hub src-port=8898
E0110 10:33:10.347227   88162 portforward.go:406] an error occurred forwarding 8898 -> 8898: error forwarding port 8898 to pod 2f0ff9cfd9391b4f40dad7b3cc4cbebe3fad5c6767483d3691ab24bc81baf8e9, uid : failed to execute portforward in network namespace "/var/run/netns/cni-86bbad86-840b-0800-0668-25c73a81e893": failed to connect to localhost:8898 inside namespace "2f0ff9cfd9391b4f40dad7b3cc4cbebe3fad5c6767483d3691ab24bc81baf8e9", IPv4: dial tcp4 127.0.0.1:8898: connect: connection refused IPv6 dial tcp6 [::1]:8898: connect: cannot assign requested address 
E0110 10:33:10.347644   88162 portforward.go:234] lost connection to pod
2023-01-10T10:33:10-06:00 ERR common.go:55 > Couldn't connect to service. error="Couldn't reach the URL: http://localhost:8899 after 3 retries!" service=kubeshark-front
2023-01-10T10:33:10-06:00 INF tapRunner.go:444 > Kubeshark is available at: url=http://localhost:8899
2023-01-10T10:33:10-06:00 WRN cleanResources.go:16 > Removing Kubeshark resources...
2023-01-10T10:33:12-06:00 ERR common.go:55 > Couldn't connect to service. error="Couldn't reach the URL: http://localhost:8898 after 3 retries!" service=kubeshark-hub
2023-01-10T10:33:12-06:00 ERR tapRunner.go:432 > Error starting worker syncer error="failed to get pods in ns: [], context canceled"
2023-01-10T10:33:12-06:00 INF tapRunner.go:437 > Hub is available at: url=http://localhost:8898
➜  ~ 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Web Browser: Microsoft Edge

**Additional context**
None

**Comment by holiiveira** [comment]
same problem here.

kubeshark 38.1

```
kubeshark tap --debug
2023-01-10T14:00:36-03:00 INF versionCheck.go:23 > Checking for a newer version...
2023-01-10T14:00:36-03:00 DBG config.go:71 > Init config is finished. config={"Config":{"Regenerate":false},"ConfigFilePath":"/home/XXXXX/.kubeshark/config.yaml","DumpLogs":false,"HeadlessMode":false,"Kube":{"ConfigPathStr":"","Context":""},"Logs":{"FileStr":""},"SelfNamespace":"kubeshark","Tap":{"AllNamespaces":false,"Debug":true,"Docker":{"ImagePullPolicy":"Always","Registry":"docker.io/kubeshark","Tag":"latest"},"DryRun":false,"Namespaces":null,"PacketCapture":"libpcap","Pcap":"","PodRegexStr":".*","Proxy":{"Front":{"DstPort":80,"SrcPort":8899},"Host":"127.0.0.1","Hub":{"DstPort":8898,"SrcPort":8898},"Worker":{"DstPort":8897,"SrcPort":8897}},"Resources":{"Hub":{"CpuLimit":"750m","CpuRequests":"50m","MemoryLimit":"1Gi","MemoryRequests":"50Mi"},"Worker":{"CpuLimit":"750m","CpuRequests":"50m","MemoryLimit":"1Gi","MemoryRequests":"50Mi"}},"ServiceMesh":true,"StorageLimit":"200MB","Tls":true}}
2023-01-10T14:00:36-03:00 INF tapRunner.go:45 > Using Docker: registry=docker.io/kubeshark tag=latest
2023-01-10T14:00:36-03:00 INF tapRunner.go:53 > Kubeshark will store the traffic up to a limit (per node). Oldest TCP streams will be removed once the limit is reached. limit=200MB
2023-01-10T14:00:36-03:00 DBG provider.go:81 > K8s client config. api-path= host=https://rancher.XXXXX.com.br/k8s/clusters/c-4l2p5 user-agent=
2023-01-10T14:00:36-03:00 INF common.go:70 > Using kubeconfig: path=/home/XXXXX/.kube/XXXXX-prd:/home/XXXXX/.kube/XXXXX-hml:/home/XXXXX/.kube/sandbox
2023-01-10T14:00:36-03:00 INF tapRunner.go:74 > Targetting pods in: namespaces=["XXXXX"]
2023-01-10T14:00:36-03:00 INF tapRunner.go:124 > New pod: grafana-XXXXX-7969c97967-mgv28
2023-01-10T14:00:36-03:00 INF tapRunner.go:124 > New pod: XXXXX-85fbbd8f8f-6vgfw
2023-01-10T14:00:36-03:00 INF tapRunner.go:124 > New pod: XXXXX-85fbbd8f8f-8b6hv
2023-01-10T14:00:36-03:00 INF tapRunner.go:124 > New pod: XXXXX-85fbbd8f8f-crfnq
2023-01-10T14:00:36-03:00 INF tapRunner.go:124 > New pod: XXXXX-85fbbd8f8f-gmcwn
2023-01-10T14:00:36-03:00 INF tapRunner.go:124 > New pod: XXXXX-85fbbd8f8f-k26tj
2023-01-10T14:00:36-03:00 INF tapRunner.go:124 > New pod: XXXXX-85fbbd8f8f-nq6sz
2023-01-10T14:00:36-03:00 INF tapRunner.go:124 > New pod: XXXXX-admin-6ffc89578c-9289j
2023-01-10T14:00:36-03:00 INF tapRunner.go:84 > Waiting for the creation of Kubeshark resources...
2023-01-10T14:00:36-03:00 INF createResources.go:108 > Successfully created a pod. pod=kubeshark-hub
2023-01-10T14:00:36-03:00 INF createResources.go:120 > Successfully created a pod. pod=kubeshark-front
2023-01-10T14:00:36-03:00 DBG versionCheck.go:38 > Fetched the latest release: elapsed-time=353.571338 local-version=38.1 upstream-version=38.1
2023-01-10T14:00:36-03:00 INF createResources.go:69 > Successfully created a service. service=kubeshark-hub
2023-01-10T14:00:36-03:00 INF createResources.go:76 > Successfully created a service. service=kubeshark-front
2023-01-10T14:00:36-03:00 DBG wait.go:13 > Waiting to finish...
2023-01-10T14:00:36-03:00 INF tapRunner.go:217 > Added pod. pod=kubeshark-hub
2023-01-10T14:00:36-03:00 INF tapRunner.go:297 > Added pod. pod=kubeshark-front
2023-01-10T14:00:37-03:00 DBG tapRunner.go:314 > Watching pod. containers-statuses=[{"image":"docker.io/kubeshark/front:latest","imageID":"","lastState":{},"name":"kubeshark-front","ready":false,"restartCount":0,"started":false,"state":{"waiting":{"reason":"ContainerCreating"}}}] phase=Pending pod=kubeshark-front
2023-01-10T14:00:37-03:00 DBG tapRunner.go:234 > Watching pod. containers-statuses=[{"image":"docker.io/kubeshark/hub:latest","imageID":"","lastState":{},"name":"kubeshark-hub","ready":false,"restartCount":0,"started":false,"state":{"waiting":{"reason":"ContainerCreating"}}}] phase=Pending pod=kubeshark-hub
2023-01-10T14:00:37-03:00 DBG tapRunner.go:392 > Watching events. event=kubeshark-hub.1739012edc21053f kind=Pod name=kubeshark-hub note="Pulling image \"docker.io/kubeshark/hub:latest\"" pod=kubeshark-hub reason=Pulling
2023-01-10T14:00:38-03:00 DBG tapRunner.go:392 > Watching events. event=kubeshark-hub.1739012f3c0c0e24 kind=Pod name=kubeshark-hub note="Successfully pulled image \"docker.io/kubeshark/hub:latest\" in 1.609222632s" pod=kubeshark-hub reason=Pulled
2023-01-10T14:00:39-03:00 DBG tapRunner.go:392 > Watching events. event=kubeshark-hub.1739012f410b60de kind=Pod name=kubeshark-hub note="Created container kubeshark-hub" pod=kubeshark-hub reason=Created
2023-01-10T14:00:39-03:00 DBG tapRunner.go:392 > Watching events. event=kubeshark-hub.1739012f487f74f4 kind=Pod name=kubeshark-hub note="Started container kubeshark-hub" pod=kubeshark-hub reason=Started
2023-01-10T14:00:39-03:00 DBG tapRunner.go:234 > Watching pod. containers-statuses=[{"containerID":"docker://78abeffceefe6490c1eb7bfb57fe614c739d2669d2fa9a1e34fe176cea761073","image":"kubeshark/hub:latest","imageID":"docker-pullable://kubeshark/hub@sha256:e5b468efcc9141d6c8be4bc005c8de56b6c3cd8ba9d65934abe1386cc7365a44","lastState":{},"name":"kubeshark-hub","ready":true,"restartCount":0,"started":true,"state":{"running":{"startedAt":"2023-01-10T17:00:39Z"}}}] phase=Running pod=kubeshark-hub
2023-01-10T14:00:39-03:00 INF proxy.go:29 > Starting proxy... namespace=kubeshark service=kubeshark-hub src-port=8898
2023-01-10T14:00:39-03:00 DBG hub.go:42 > Not ready yet! error="got response with status code: 401, body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Unauthorized\",\"reason\":\"Unauthorized\",\"code\":401};" url=http://localhost:8898
2023-01-10T14:00:39-03:00 DBG tapRunner.go:314 > Watching pod. containers-statuses=[{"containerID":"docker://357fca74da62d2487c67ce8c3f156dcc40edf2eacf081cbf37e22e7ca9637d99","image":"kubeshark/front:latest","imageID":"docker-pullable://kubeshark/front@sha256:cba3f9e9fde583ccebcb9097bc7729f296518a71c5808c800e20aaeb37a7af6f","lastState":{},"name":"kubeshark-front","ready":false,"restartCount":0,"started":true,"state":{"running":{"startedAt":"2023-01-10T17:00:38Z"}}}] phase=Running pod=kubeshark-front
2023-01-10T14:00:39-03:00 INF proxy.go:29 > Starting proxy... namespace=kubeshark service=kubeshark-front src-port=8899
2023-01-10T14:00:39-03:00 DBG hub.go:42 > Not ready yet! error="got response with status code: 401, body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Unauthorized\",\"reason\":\"Unauthorized\",\"code\":401};" url=http://localhost:8899
2023-01-10T14:00:40-03:00 DBG hub.go:42 > Not ready yet! error="got response with status code: 401, body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Unauthorized\",\"reason\":\"Unauthorized\",\"code\":401};" url=http://localhost:8898
2023-01-10T14:00:40-03:00 DBG hub.go:42 > Not ready yet! error="got response with status code: 401, body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Unauthorized\",\"reason\":\"Unauthorized\",\"code\":401};" url=http://localhost:8899
2023-01-10T14:00:41-03:00 DBG hub.go:42 > Not ready yet! error="got response with status code: 401, body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Unauthorized\",\"reason\":\"Unauthorized\",\"code\":401};" url=http://localhost:8898
2023-01-10T14:00:41-03:00 DBG hub.go:42 > Not ready yet! error="got response with status code: 401, body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Unauthorized\",\"reason\":\"Unauthorized\",\"code\":401};" url=http://localhost:8899
2023-01-10T14:00:42-03:00 ERR common.go:33 > Couldn't connect using proxy, stopping proxy and trying to create port-forward..
2023-01-10T14:00:42-03:00 INF proxy.go:117 > Starting proxy using port-forward method... dst-port=8898 namespace=kubeshark pod=kubeshark-hub src-port=8898
2023-01-10T14:00:42-03:00 DBG proxy.go:158 > HTTP dialer URL: url=https://rancher.XXXXX.com.br/k8s/clusters/c-4l2p5/api/v1/namespaces/kubeshark/pods/kubeshark-hub/portforward
2023-01-10T14:00:42-03:00 DBG hub.go:42 > Not ready yet! error="Get \"http://localhost:8898/echo\": dial tcp [::1]:8898: connect: connection refused" url=http://localhost:8898
2023-01-10T14:00:42-03:00 ERR common.go:33 > Couldn't connect using proxy, stopping proxy and trying to create port-forward..
2023-01-10T14:00:42-03:00 INF proxy.go:117 > Starting proxy using port-forward method... dst-port=80 namespace=kubeshark pod=kubeshark-hub src-port=8899
2023-01-10T14:00:42-03:00 DBG proxy.go:158 > HTTP dialer URL: url=https://rancher.XXXXX.com.br/k8s/clusters/c-4l2p5/api/v1/namespaces/kubeshark/pods/kubeshark-hub/portforward
2023-01-10T14:00:42-03:00 DBG hub.go:42 > Not ready yet! error="Get \"http://localhost:8899\": dial tcp [::1]:8899: connect: connection refused" url=http://localhost:8899
E0110 14:00:43.787572  741089 portforward.go:406] an error occurred forwarding 8898 -> 8898: error forwarding port 8898 to pod 82608e3d9e29b32d9ce63480d306f766840b55da374d44255fa82cb945abf402, uid : exit status 1: 2023/01/10 17:00:43 socat[2877622] E connect(5, AF=2 127.0.0.1:8898, 16): Connection refused
E0110 14:00:43.787984  741089 portforward.go:234] lost connection to pod
2023-01-10T14:00:43-03:00 DBG hub.go:42 > Not ready yet! error="Get \"http://localhost:8898/echo\": EOF" url=http://localhost:8898
2023-01-10T14:00:43-03:00 DBG hub.go:42 > Not ready yet! error="got response with status code: 404, body: 404 page not found" url=http://localhost:8899
2023-01-10T14:00:44-03:00 DBG hub.go:42 > Not ready yet! error="Get \"http://localhost:8898/echo\": dial tcp [::1]:8898: connect: connection refused" url=http://localhost:8898
2023-01-10T14:00:44-03:00 DBG hub.go:42 > Not ready yet! error="got response with status code: 404, body: 404 page not found" url=http://localhost:8899
2023-01-10T14:00:45-03:00 ERR common.go:55 > Couldn't connect to service. error="Couldn't reach the URL: http://localhost:8898 after 3 retries!" service=kubeshark-hub
2023-01-10T14:00:45-03:00 ERR tapRunner.go:432 > Error starting worker syncer error="failed to get pods in ns: [XXXXX], context canceled"
2023-01-10T14:00:45-03:00 INF tapRunner.go:437 > Hub is available at: url=http://localhost:8898
2023-01-10T14:00:45-03:00 DBG wait.go:20 > Context done.
2023-01-10T14:00:45-03:00 DBG tapRunner.go:422 > Watching pod events, context done. pod=kubeshark-hub
2023-01-10T14:00:45-03:00 DBG tapRunner.go:274 > Watching pod, context done. pod=kubeshark-hub
2023-01-10T14:00:45-03:00 WRN cleanResources.go:16 > Removing Kubeshark resources...
2023-01-10T14:00:45-03:00 ERR common.go:55 > Couldn't connect to service. error="Couldn't reach the URL: http://localhost:8899 after 3 retries!" service=kubeshark-front
2023-01-10T14:00:45-03:00 INF tapRunner.go:444 > Kubeshark is available at: url=http://localhost:8899
2023-01-10T14:00:45-03:00 DBG tapRunner.go:353 > Watching pod, context done. pod=kubeshark-front
2023-01-10T14:00:45-03:00 DBG wait.go:13 > Waiting to finish...
```

**Comment by mertyildiran** [comment]
Do `kubeshark-hub` and `kubeshark-front` pods are actually created? If so what are their logs? The reason could be the pull of their images delayed too much.

**Comment by holiiveira** [comment]
Are created, this is the log I see:

`kubeshark-front`:

```
Provided flags:
--config-name = ./runtime-env.js
--env-file = ./.env
Your environment variables will be available on 'window.__RUNTIME_CONFIG__'
./runtime-env.js does not exist. Creating one...
Successfully generated your runtime-env config!
Result: window.__RUNTIME_CONFIG__ = {"REACT_APP_DEFAULT_FILTER":"timestamp >= now()","REACT_APP_HUB_HOST":" ","REACT_APP_HUB_PORT":"8898"};
Thank you for using runtime-env-cra!
2023/01/10 19:58:52 [notice] 1#1: using the "epoll" event method
2023/01/10 19:58:52 [notice] 1#1: nginx/1.22.0
2023/01/10 19:58:52 [notice] 1#1: built by gcc 11.2.1 20220219 (Alpine 11.2.1_git20220219)
2023/01/10 19:58:52 [notice] 1#1: OS: Linux 5.4.0-131-generic
2023/01/10 19:58:52 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/01/10 19:58:52 [notice] 1#1: start worker processes
2023/01/10 19:58:52 [notice] 1#1: start worker process 18
2023/01/10 19:58:52 [notice] 1#1: start worker process 19
2023/01/10 19:58:52 [notice] 1#1: start worker process 20
2023/01/10 19:58:52 [notice] 1#1: start worker process 21
2023/01/10 19:59:04 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2023/01/10 19:59:04 [notice] 21#21: gracefully shutting down
2023/01/10 19:59:04 [notice] 20#20: gracefully shutting down
2023/01/10 19:59:04 [notice] 20#20: exiting
2023/01/10 19:59:04 [notice] 19#19: gracefully shutting down
2023/01/10 19:59:04 [notice] 21#21: exiting
2023/01/10 19:59:04 [notice] 19#19: exiting
2023/01/10 19:59:04 [notice] 18#18: gracefully shutting down
2023/01/10 19:59:04 [notice] 18#18: exiting
2023/01/10 19:59:04 [notice] 21#21: exit
2023/01/10 19:59:04 [notice] 19#19: exit
2023/01/10 19:59:04 [notice] 20#20: exit
2023/01/10 19:59:04 [notice] 18#18: exit
2023/01/10 19:59:04 [notice] 1#1: signal 17 (SIGCHLD) received from 19
2023/01/10 19:59:04 [notice] 1#1: worker process 18 exited with code 0
2023/01/10 19:59:04 [notice] 1#1: worker process 19 exited with code 0
2023/01/10 19:59:04 [notice] 1#1: worker process 21 exited with code 0
2023/01/10 19:59:04 [notice] 1#1: signal 29 (SIGIO) received
2023/01/10 19:59:04 [notice] 1#1: signal 17 (SIGCHLD) received from 20
2023/01/10 19:59:04 [notice] 1#1: worker process 20 exited with code 0
2023/01/10 19:59:04 [notice] 1#1: exit
```

`kubeshark-hub`:

```
2023-01-10T19:58:51Z INF pkg/misc/data.go:26 > Set the data directory to: data-dir=data
2023-01-10T19:58:51Z INF pkg/worker/hosts.go:28 > Added worker host: host=127.0.0.1:8897
2023-01-10T19:58:51Z INF main.go:35 > Initializing the Hub...
2023-01-10T19:58:51Z INF server/server.go:65 > Starting the server...
```

**Comment by mertyildiran** [comment]
@holiiveira do you see `8899` or `8898` in the output of `sudo lsof -i -P -n | grep LISTEN`?

**Comment by holiiveira** [comment]
> @holiiveira do you see `8899` or `8898` in the output of `sudo lsof -i -P -n | grep LISTEN`?

Yes:

```
kubeshark 788251 holiveira   10u  IPv4 1874184      0t0  TCP 127.0.0.1:8898 (LISTEN)
kubeshark 788251 holiveira   11u  IPv6 1874185      0t0  TCP [::1]:8898 (LISTEN)
kubeshark 788251 holiveira   13u  IPv4 1884286      0t0  TCP 127.0.0.1:8899 (LISTEN)
kubeshark 788251 holiveira   14u  IPv6 1884287      0t0  TCP [::1]:8899 (LISTEN)
```



> The reason could be the pull of their images delayed too much.

I did a test using our private registry, nothing changed.

`Successfully pulled image "registry.XXXXX.com.br/library/kubeshark/front:latest" in 129.024374ms`

**Comment by mertyildiran** [comment]
@holiiveira how did you end up with those hanging services on `8899` and `8898`? Try shutting them down or use different ports with `--proxy-front-port` and `--proxy-hub-port` options.

**Comment by mertyildiran** [comment]
@holiiveira do you use Rancher? Because somebody else also reported `401` problem with Rancher.

**Comment by holiiveira** [comment]
> how did you end up with those hanging services on `8899` and `8898`?

It's actually not hanging, I ran the command at the same time as kubeshark tap - I thought it was to check if the proxy was ok.

> do you use Rancher?

Yes.

**Comment by ognjenVlad** [comment]
I have same behaviour with EKS cluster https://github.com/kubeshark/kubeshark/issues/1292

**Comment by mertyildiran** [comment]
This issue is fixed with [the release 38.3](https://github.com/kubeshark/kubeshark/releases/tag/38.3).

**Comment by talkain** [comment]
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/2634927/212638923-28d80edb-c71f-4897-9285-549850680d9a.png">

@mertyildiran thanks for pushing this one! there is still an issue with 38.3 and my EKS
(macOS 13.1)

**Comment by PixiBixi** [comment]
Also got a 401 w/ Rancher, using Kubeshark last version :/

**Comment by PixiBixi** [comment]
Nice its now fixed, even for Rancher! :)

**Comment by azamora-zsc** [comment]
Actually, I'm getting the same error using the latest version available now (38.5) with EKS and MacOs Ventura. Is anybody having the same behavior in a similar setting?

**Comment by kong62** [comment]
error="flag \"proxy.proxy.host\" not found"
```
# kubeshark proxy --proxy-host "0.0.0.0"
2023-03-23T14:03:54+08:00 INF versionCheck.go:23 > Checking for a newer version...
2023-03-23T14:03:54+08:00 WRN config.go:157 > error="flag \"proxy.proxy.host\" not found"
2023-03-23T14:03:54+08:00 INF common.go:69 > Using kubeconfig: path=/root/.kube/config
2023-03-23T14:03:54+08:00 INF proxy.go:29 > Starting proxy... namespace=kubeshark service=kubeshark-hub src-port=8898
2023-03-23T14:03:54+08:00 INF proxyRunner.go:132 > Hub is available at: url=http://localhost:8898
2023-03-23T14:03:54+08:00 INF proxy.go:29 > Starting proxy... namespace=kubeshark service=kubeshark-front src-port=8899
2023-03-23T14:03:54+08:00 INF proxyRunner.go:132 > Kubeshark is available at: url=http://localhost:8899
```
